<a href="https://colab.research.google.com/github/Dcipher4/Daily-Coding/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

# array = (1 ,3, 5, 7, 9, 2, 4, 6, 8)
array = np.array ((1 ,3, 5, 7, 9, 2, 4, 6, 8.4))
print(array)
print(type(array))
print(array.dtype)


2.0.2
[1.  3.  5.  7.  9.  2.  4.  6.  8.4]
<class 'numpy.ndarray'>
float64


In [ ]:
import numpy as np
print(np.__version__)

array = np.array((1 ,3, 5, 7, 9, 2, 4, 6, 8))
# array = np.array ((1 ,3, 5, 7, 9, 2, 4, 6, 8.4))
print(array)
print(type(array))
print(array.dtype)


2.0.2
[1 3 5 7 9 2 4 6 8]
<class 'numpy.ndarray'>
int64


In [ ]:
import numpy as np
print(np.__version__)

array = np.array((1 ,3, 5, 7, 9, 2, 4, 6, 8), dtype = 'float')
# array = np.array ((1 ,3, 5, 7, 9, 2, 4, 6, 8.4))
print(array)
print(type(array))
print(array.dtype)

2.0.2
[1. 3. 5. 7. 9. 2. 4. 6. 8.]
<class 'numpy.ndarray'>
float64


In [ ]:
# now lkets create a 2d array
arr = np.array ([[10,20,30,40],[15,25,35,45]], dtype = 'float')
print (arr)
print(type(arr))
print(arr.dtype)
print(arr[0,1])


[[10. 20. 30. 40.]
 [15. 25. 35. 45.]]
<class 'numpy.ndarray'>
float64
20.0


In [27]:
import numpy as np  # First, we bring in NumPy—it’s a must for working with arrays.

# Here’s our 3D array. Think of it as a stack of 2D grids.
arr3d = np.array([
    [[10, 20, 30], [40, 50, 60]],
    [[11, 21, 31], [41, 51, 61]],
    [[12, 22, 32], [42, 52, 62]]
])

print(arr3d)  # Just checking out the whole array.

# Grabbing specific elements based on their positions.
print(arr3d[0, 1, 2])  # Picks the element at row 0, sub-row 1, position 2 (should be 60).
print(arr3d.shape)  # Shape tells us the array dimensions. (3 layers, 2 rows, 3 columns)
print(arr3d[2, 1, 2])  # Another lookup—row 2, sub-row 1, position 2 (should be 62).

# Some basic stats—useful for quick data analysis.
print(np.sum(arr3d))  # Total sum of all elements.
print(np.median(arr3d))  # Middle value if you sorted everything.
print(np.mean(arr3d))  # Average of all values.
print(np.std(arr3d))  # Standard deviation—how spread out the numbers are.
print(np.var(arr3d))  # Variance—another way to measure spread.

# Finding the extremes in the array.
print(np.min(arr3d))  # The smallest number in our dataset.
print(np.max(arr3d))  # The biggest one.
print(np.argmin(arr3d))  # Index position of the smallest value.
print(np.argmax(arr3d))  # Index position of the largest value.

# Sorting and transforming the array.
print(np.sort(arr3d))  # Sorts each row separately—doesn’t mess up the structure.
print(np.prod(arr3d))  # Multiplies all elements together.

# Cumulative operations—useful for running totals or progressive calculations.
print(np.cumsum(arr3d))  # Adds up numbers step by step.
print(np.cumprod(arr3d))  # Keeps multiplying numbers progressively.

# Some handy functions for analyzing patterns.
print(np.unique(arr3d))  # Removes duplicates—gives you the distinct values.
print(np.diff(arr3d))  # Shows how much each element changes compared to the previous one.

# Playing with the shape and order of the array.
print(np.flip(arr3d))  # Completely flips the array—like turning a photo upside down.
print(np.flip(arr3d, axis=0))  # Flips along the first axis—changes the order of layers.

# Identifying non-zero values.
print(np.nonzero(arr3d))  # Tells you the positions of all non-zero elements





# the comments were written by an AI to help me understand the codes later on

[[[10 20 30]
  [40 50 60]]

 [[11 21 31]
  [41 51 61]]

 [[12 22 32]
  [42 52 62]]]
60
(3, 2, 3)
62
648
36.0
36.0
17.09775813764288
292.3333333333333
10
62
0
17
[[[10 20 30]
  [40 50 60]]

 [[11 21 31]
  [41 51 61]]

 [[12 22 32]
  [42 52 62]]]
4517244343857184768
[ 10  30  60 100 150 210 221 242 273 314 365 426 438 460 492 534 586 648]
[                  10                  200                 6000
               240000             12000000            720000000
           7920000000         166320000000        5155920000000
      211392720000000    10781028720000000   657642751920000000
  7891713023040000000  7596989843494035456  3296002033584963584
 -9141867179107942400  4238252602835337216  4517244343857184768]
[10 11 12 20 21 22 30 31 32 40 41 42 50 51 52 60 61 62]
[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]

 [[10 10]
  [10 10]]]
[[[62 52 42]
  [32 22 12]]

 [[61 51 41]
  [31 21 11]]

 [[60 50 40]
  [30 20 10]]]
[[[12 22 32]
  [42 52 62]]

 [[11 21 31]
  [41 51 61]]

 [[10 20 30]
 